import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"
]

[window]
dynamic_padding = true
opacity = 0.9

  [window.padding]
  x = 5
  y = 2

[font]
size = 11

  [font.normal]
  family = "JetBrains Mono NF"
  style = "Regular"

  [font.offset]
  x = 0
  y = 1
